[platformio]
default_envs = t-camera-sim
src_dir = src

[env:t-camera-sim]
platform = espressif32@6.3.0
board = esp32s3box
framework = arduino

upload_speed = 921600
monitor_speed = 115200
monitor_filters =
    default
    esp32_exception_decoder

build_flags =
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DCORE_DEBUG_LEVEL=0
    -DBOARD_HAS_PSRAM
    -DCAMERA_MODEL_TTGO_T_CAM_SIM

lib_deps =
    adafruit/RTClib
    adafruit/Adafruit MCP23017 Arduino Library@^2.2.0

lib_ignore =
    TFT_eSPI

board_build.partitions = default_16MB.csv
